name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APKs
      run: flutter build apk --release

    - name: Archive APKs
      run: |
        mkdir -p artifacts
        mv build/app/outputs/flutter-apk/*.apk artifacts/

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install GitHub CLI
        run: |
          sudo apt-get install unzip
          GH_VERSION=$(curl -s https://api.github.com/repos/cli/cli/releases/latest | jq -r .tag_name)
          GH_URL="https://github.com/cli/cli/releases/download/$GH_VERSION/gh_$GH_VERSION_linux_amd64.tar.gz"
          curl -sL $GH_URL -o gh.tar.gz
          tar tzf gh.tar.gz
          tar xzf gh.tar.gz
          sudo mv gh_$GH_VERSION_linux_amd64/gh /usr/local/bin/

      - name: Create Release
        run: |
          gh release create <tag_name> release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}